"""add_indexes_and_cascades

Revision ID: 34beb1e17e08
Revises: a2c3d4e5f6g7
Create Date: 2026-05-31 18:27:29.803620
"""
# 导入模块: from typing
from typing import Sequence, Union

# 导入模块: from alembic
from alembic import op
# 导入模块: sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34beb1e17e08'
down_revision: Union[str, None] = 'a2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analyses', 'result_json',
               # 初始化变量 existing_type
               existing_type=sa.VARCHAR(),
               # 初始化变量 type_
               type_=app.utils.encryption.EncryptedText(),
               # 初始化变量 existing_nullable
               existing_nullable=False)
    op.alter_column('analyses', 'mode',
               # 初始化变量 existing_type
               existing_type=sa.VARCHAR(length=20),
               # 初始化变量 type_
               type_=sa.Enum('auto', 'single', 'multi', name='analysis_mode_enum', create_constraint=True),
               # 初始化变量 nullable
               nullable=False)
    op.create_index(op.f('ix_analyses_case_id'), 'analyses', ['case_id'], unique=False)
    op.create_index('ix_analyses_case_id_created_at', 'analyses', ['case_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_analyses_mode'), 'analyses', ['mode'], unique=False)
    op.alter_column('cases', 'status',
               # 初始化变量 existing_type
               existing_type=sa.VARCHAR(length=20),
               # 初始化变量 type_
               type_=sa.Enum('pending', 'analyzing', 'completed', 'closed', name='case_status_enum', create_constraint=True),
               # 初始化变量 nullable
               nullable=False)
    op.create_index('ix_cases_status_created_at', 'cases', ['status', 'created_at'], unique=False)
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.create_foreign_key(None, 'cases', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'knowledge_entries', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_entries', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_entries', 'users', ['verified_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'knowledge_entries', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_index('ix_lr_created_at', 'legal_rules', ['created_at'], unique=False)
    op.create_index('ix_lr_source_law', 'legal_rules', ['source_law'], unique=False)
    op.create_index('ix_mv_created_at', 'model_versions', ['created_at'], unique=False)
    op.create_unique_constraint('uq_mv_name_version', 'model_versions', ['model_name', 'version'])
    op.create_index('ix_system_logs_action', 'system_logs', ['action'], unique=False)
    op.create_index('ix_system_logs_level_created_at', 'system_logs', ['log_level', 'created_at'], unique=False)
    op.create_index('ix_system_logs_username', 'system_logs', ['username'], unique=False)
    op.add_column('users', sa.Column('login_failed_count', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'role',
               # 初始化变量 existing_type
               existing_type=sa.VARCHAR(length=20),
               # 初始化变量 type_
               type_=sa.Enum('admin', 'user', 'analyst', name='user_role_enum', create_constraint=True),
               # 初始化变量 existing_nullable
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               # 初始化变量 existing_type
               existing_type=sa.BOOLEAN(),
               # 初始化变量 nullable
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               # 初始化变量 existing_type
               existing_type=sa.BOOLEAN(),
               # 初始化变量 nullable
               nullable=True)
    op.alter_column('users', 'role',
               # 初始化变量 existing_type
               existing_type=sa.Enum('admin', 'user', 'analyst', name='user_role_enum', create_constraint=True),
               # 初始化变量 type_
               type_=sa.VARCHAR(length=20),
               # 初始化变量 existing_nullable
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'login_failed_count')
    op.drop_index('ix_system_logs_username', table_name='system_logs')
    op.drop_index('ix_system_logs_level_created_at', table_name='system_logs')
    op.drop_index('ix_system_logs_action', table_name='system_logs')
    op.drop_constraint('uq_mv_name_version', 'model_versions', type_='unique')
    op.drop_index('ix_mv_created_at', table_name='model_versions')
    op.drop_index('ix_lr_source_law', table_name='legal_rules')
    op.drop_index('ix_lr_created_at', table_name='legal_rules')
    op.drop_constraint(None, 'knowledge_entries', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_entries', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_entries', 'users', ['verified_by'], ['id'])
    op.create_foreign_key(None, 'knowledge_entries', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.create_foreign_key(None, 'cases', 'users', ['created_by'], ['id'])
    op.drop_index('ix_cases_status_created_at', table_name='cases')
    op.alter_column('cases', 'status',
               # 初始化变量 existing_type
               existing_type=sa.Enum('pending', 'analyzing', 'completed', 'closed', name='case_status_enum', create_constraint=True),
               # 初始化变量 type_
               type_=sa.VARCHAR(length=20),
               # 初始化变量 nullable
               nullable=True)
    op.drop_index(op.f('ix_analyses_mode'), table_name='analyses')
    op.drop_index('ix_analyses_case_id_created_at', table_name='analyses')
    op.drop_index(op.f('ix_analyses_case_id'), table_name='analyses')
    op.alter_column('analyses', 'mode',
               # 初始化变量 existing_type
               existing_type=sa.Enum('auto', 'single', 'multi', name='analysis_mode_enum', create_constraint=True),
               # 初始化变量 type_
               type_=sa.VARCHAR(length=20),
               # 初始化变量 nullable
               nullable=True)
    op.alter_column('analyses', 'result_json',
               # 初始化变量 existing_type
               existing_type=app.utils.encryption.EncryptedText(),
               # 初始化变量 type_
               type_=sa.VARCHAR(),
               # 初始化变量 existing_nullable
               existing_nullable=False)
    # ### end Alembic commands ###
