"""知识库服务统一入口.

提供知识库相关功能的统一导入接口，包括数据访问、分析和管理功能。
"""
from app.services.knowledge.repository import (
    add_entry_relation,
    add_entry_tag,
    create_entry,
    create_tag,
    delete_entry,
    ensure_fts_table,
    get_all_tags,
    get_entry,
    get_entry_relations,
    get_entry_tags,
    get_entries_paginated,
    get_fts_count,
    remove_entry_from_fts,
    remove_entry_tag,
    search_entries,
    sync_entry,
    update_entry,
)
from app.services.knowledge.analyzer import (
    KnowledgeQAService,
    auto_link_entries,
    find_related_entries,
    get_graph_data,
    get_legal_rules,
    get_node_neighbors,
    get_shortest_path,
)
from app.services.knowledge.manager import (
    BatchImportResult,
    DecayStatistics,
    ImportResult,
    KnowledgeLifecycleScheduler,
    LintIssue,
    LintReport,
    ScheduleConfig,
    apply_decay,
    batch_import_from_cases,
    extract_metadata_with_llm,
    import_from_case,
    import_from_document,
    lint_knowledge_base,
    run_decay_sync,
    run_lint_sync,
    supersede_entry,
    update_confidence,
)

__all__ = [
    # 数据访问层 (repository.py)
    "get_entries_paginated",
    "get_entry",
    "create_entry",
    "update_entry",
    "delete_entry",
    "get_entry_relations",
    "add_entry_relation",
    "get_entry_tags",
    "add_entry_tag",
    "remove_entry_tag",
    "get_all_tags",
    "create_tag",
    "ensure_fts_table",
    "sync_entry",
    "remove_entry_from_fts",
    "get_fts_count",
    "search_entries",
    # 分析层 (analyzer.py)
    "get_legal_rules",
    "get_graph_data",
    "get_node_neighbors",
    "get_shortest_path",
    "find_related_entries",
    "auto_link_entries",
    "KnowledgeQAService",
    # 管理层 (manager.py)
    "import_from_document",
    "import_from_case",
    "batch_import_from_cases",
    "extract_metadata_with_llm",
    "update_confidence",
    "apply_decay",
    "lint_knowledge_base",
    "supersede_entry",
    "run_decay_sync",
    "run_lint_sync",
    "ImportResult",
    "BatchImportResult",
    "DecayStatistics",
    "LintIssue",
    "LintReport",
    "ScheduleConfig",
    "KnowledgeLifecycleScheduler",
]
